route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'yyyzzz9914@gmail.com'
        auth_password: "mhfn qczd rsny wvkq"
        from: 'yyyzzz9914@gmail.com'
        to: 'yaryna.ostapchuk.email@gmail.com'
        tls_config:
          insecure_skip_verify: true