services:

  prometheus:
    image: docker.io/prom/prometheus:v2.54.0
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana-oss:11.1.4
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  nginx:
    image: docker.io/library/nginx:1.26.2-alpine
    container_name: nginx
    ports:
      - 80:80
      # (optional) uncomment the line below to enable HTTPS
      # - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - grafana

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local