services:

  prometheus:
    image: docker.io/prom/prometheus:v2.54.0
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "4317"
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    volumes:
      - ./tempo/tempo-config.yaml:/etc/tempo.yml

  loki:
    image: grafana/loki:main
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml

  grafana:
    image: docker.io/grafana/grafana-oss:11.1.4
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards_config/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/etc/grafana/dashboards
    restart: unless-stopped
    depends_on:
      - loki
      - tempo

  nginx:
    image: docker.io/library/nginx:1.26.2-alpine
    container_name: nginx
    ports:
      - 80:80
      # (optional) uncomment the line below to enable HTTPS
      # - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - grafana

  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4343:4317" #grpc
      - "4344:4318" #http
    command: ['--config=/etc/otelcol-contrib/config.yaml']
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - loki
      - tempo

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local