receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - "*"

exporters:
  otlphttp/logs:
    endpoint: "http://172.18.0.4:3100/otlp"
    tls:
      insecure: true
  otlp:
    endpoint: tempo:4317 # tempo container host & port
    tls:
      insecure: true

processors:
  # batch metrics before sending to reduce API usage
  batch:

service:
    pipelines:
        logs:
            receivers: [otlp]
            exporters: [otlphttp/logs]
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
