receivers:
  otlp:
    protocols:
      http:

exporters:
  otlphttp/logs:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true
  otlp:
    endpoint: tempo:4317 # tempo container host & port
    tls:
      insecure: true

processors:
  # batch metrics before sending to reduce API usage
  batch:

service:
    pipelines:
        logs:
            receivers: [otlp]
            exporters: [otlphttp/logs]
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
