receivers:
  otlp/traces:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4343"
  otlp/logs:
    protocols:
      grpc:
        endpoint: "0.0.0.0:9211"


exporters:
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

processors:
  # batch metrics before sending to reduce API usage
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp/logs]
      exporters: [otlphttp/loki]
    traces:
      receivers: [otlp/traces]
      processors: [batch]
      exporters: [otlp/tempo]
